services:
  db:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: ${TZ}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db-store:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf

  fastify:
    build:
      context: .
      dockerfile: Dockerfile.fastify
    container_name: fastify_app
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=mysql://root:${ROOT_PASS}@db:3306/meibo_app
    depends_on:
      - db
    volumes:
      - ./fastify-app:/app
      - /app/node_modules
      - /app/dist
    working_dir: /app
    command: sh -c "npx prisma migrate deploy && node seed.js && npm run build && npm start"
      
  hono:
    build:
      context: .
      dockerfile: Dockerfile.hono
    container_name: hono_app
    ports:
      - "3000:3000" 
    environment:
      - API_URL=http://fastify:3001
      - FASTIFY_API_URL=http://fastify:3001
    depends_on:
      - db
      - fastify
    volumes:
      - ./front:/app
      - /app/node_modules
      - /app/dist
    working_dir: /app

volumes:
  db-store: