version: "3.9"
services:
  fastify:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - my-node:/usr/src/app/node_modules
    command: npm run start

volumes:
  my-node:
    driver: local
